### PR TITLE
Update microgravity Dockerfile with no root

### PR DESCRIPTION
**Pull request by AngelOnFira**

### CODE REVIEW

**Comment by AngelOnFira** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #18** <a href="https://app.graphite.dev/github/pr/rivet-gg/examples/18?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
    * **PR #19** <a href="https://app.graphite.dev/github/pr/rivet-gg/examples/19?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/examples/18?utm_source=stack-comment).

**Comment by AngelOnFira** [comment]
### Merge activity

* **Feb 1, 7:37 PM EST**: @AngelOnFira started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/rivet-gg/examples/18).
* **Feb 1, 7:37 PM EST**: @AngelOnFira merged this pull request with [Graphite](https://app.graphite.dev/github/pr/rivet-gg/examples/18).

**Review by MasterPtato — APPROVED** [review]
@AngelOnFira do you know why git has to be installed in this container?

**Comment by AngelOnFira** [comment]
Not sure. I'll make a ticket to check that out, I intend on going through and cleaning lots of the other Dockerfiles in this repo, so I'll check it out then.

**Pull request merged**
